// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PLUGIN_NAME = 'osmose_icons';
  static const String PLUGIN_VERSION = '1.0.0';
  static const String ICOMOON = 'icomoon';
}
